from django.db import models
from datetime import datetime
from django.urls import reverse
# User : first_name, last_name, email, password, username
# Post : user, text, created_at, updated_at
# Foreign key relationship exists between User and Post on Model level not on Database level.
# this would be a many to one relationship ans many posts can be generated by a user

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length = 254)
    password = models.CharField(max_length=100)
    username = models.CharField(max_length=50,primary_key=True)

    def __str__(self):
        return str(self.username)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return str(self.user)
    def get_absolute_url (self):
        return reverse('fullpost',args=str(self.id))



